/* tslint:disable */
/* eslint-disable */
/*
AlexisHR API

<h1 id=\"introduction\">Introduction</h1>
<p>
  AlexisHR API is currently in preview. This means that small, backward
  incompatible changes might be introduced while in preview. The changes will be
  documented and communicated.
  <a
    href=\"https://cdn.forms-content.sg-form.com/56c6a65c-90a2-11eb-a700-a6de1aea3a1a\"
    target=\"_blank\"
    ><button>Subscribe to updates</button></a
  >
</p>

<h1 id=\"authentication\">Authentication</h1>
<pre class=\"click-to-expand-wrapper is-snippet-wrapper language-undefined\">
<code class=\"is-highlighted language-bash\">curl https://api.alexishr.com/v1/employee \\
  -H \"Authorization: Bearer &lt;your_access_token&gt;\"</code>
</pre>
<p>
  Authenticate your account when using the API by including your secret Access
  Token in the request.
  <a href=\"https://app.alexishr.com/access-tokens\">Manage your Access Tokens</a
  >.
</p>
<p>
  Authentication is performed by passing the Access Token in the Authorization
  header.
</p>
<hr />

<h1 id=\"structure\">Structure</h1>
<p>
  You will find the structure of the API to be highly uniform and consistent.
  Typically every resource can be accessed via a top level endpoint, such as
  <code>/v1/employee</code>. For every such resource, you can perform some of
  the following operations:
</p>
<h2>Operations</h2>
<table>
  <tr>
    <td>GET /v1/:resource</td>
    <td>List all objects of this type</td>
  </tr>
  <tr>
    <td>GET /v1/:resource/:id</td>
    <td>Retrieve a resource by id</td>
  </tr>
  <tr>
    <td>POST /v1/:resource</td>
    <td>Create a resource of this type</td>
  </tr>
  <tr>
    <td>PATCH /v1/:resource/:id</td>
    <td>Update the resource by id</td>
  </tr>
  <tr>
    <td>DELETE /v1/:resource/:id</td>
    <td>Delete the resource by id</td>
  </tr>
</table>
<hr />

<h1 id=\"roles\">Roles</h1>
<p>The Access Tokens will have owner permission on the account</p>
<hr />

<h1 id=\"filters\">Filters</h1>
<p>
  Some of the list endpoints allow to filter results by certain conditions.
  Refer to specific resources to find out what criteria are allowed. Below is a
  list of the different conditions.
</p>

<h4 id=\"eq\"><code>$eq</code></h4>
<p>Find all results matching the attribute value specified.</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[fieldName][$eq]=value</code></pre>
</div>
<p>Can also be simplified like this.</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[fieldName]=value</code></pre>
</div>

<h4 id=\"neq\"><code>$neq</code></h4>
<p>Find all results not matching the attribute value specified.</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[fieldName][$neq]=value</code></pre>
</div>

<h4 id=\"gt\"><code>$gt</code>, <code>$gte</code></h4>
<p>
  Find all results where the value is more (<code>$gt</code>) or more and equal
  (<code>$gte</code>) to a given value.
</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[startDate][$gte]=2020-01-01</code></pre>
</div>
<hr />

<h4 id=\"lt\"><code>$lt</code>, <code>$lte</code></h4>
<p>
  Find all results where the value is less (<code>$lt</code>) or less and equal
  (<code>$lte</code>) to a given value.
</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[startDate][$lte]=2020-01-01</code></pre>
</div>
<hr />

<h4 id=\"in\"><code>$in</code>, <code>$nin</code></h4>
<p>
  Find all results matching (<code>$in</code>) or not matching
  (<code>$nin</code>) any of the attribute values specified.
</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[fieldName][$in][]=value1&filters[fieldName][$in][]=value2</code></pre>
</div>
<hr />

<h4 id=\"between\"><code>$between</code></h4>
<p>Find all results between two values specified.</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[startDate][$between][]=2020-01-01&filters[startDate][$between][]=2020-12-31</code></pre>
</div>
<hr />

<h1 id=\"versioning\">Versioning</h1>
<p>
  Each version of the API is guaranteed to be compatible with the resources of
  the same version. When we make breaking changes to the API a new version will
  be published
</p>
<hr />

<h1 id=\"changelog\">Changelog</h1>
<h3>2023-12-20</h3>
<p>Field [updated] added for filter & select for Get Many Employments and Get Many Employees.</p>
<h3>2021-03-15</h3>
<p>First draft was published</p>
<hr />

# Authentication

<!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: v1-preview
Contact: support@alexishr.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BadRequestResponse } from '../models';
// @ts-ignore
import { ChildGetManyFiltersParameter } from '../models';
// @ts-ignore
import { ChildGetManySortParameter } from '../models';
// @ts-ignore
import { ChildGetOneResponseMapped } from '../models';
// @ts-ignore
import { ChildResponseMapped } from '../models';
// @ts-ignore
import { ChildrenGetManyResponseMapped } from '../models';
// @ts-ignore
import { CreateChildRequest } from '../models';
// @ts-ignore
import { EmptyResponseMapped } from '../models';
// @ts-ignore
import { ForbiddenResponse } from '../models';
// @ts-ignore
import { InternalServerErrorResponse } from '../models';
// @ts-ignore
import { NotFoundResponse } from '../models';
// @ts-ignore
import { UnauthorizedResponse } from '../models';
// @ts-ignore
import { UpdateChildRequest } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * ChildApi - axios parameter creator
 * @export
 */
export const ChildApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create One Child
         * @summary Create One Child
         * @param {CreateChildRequest} createChildRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOne: async (createChildRequest: CreateChildRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createChildRequest' is not null or undefined
            assertParamExists('createOne', 'createChildRequest', createChildRequest)
            const localVarPath = `/child`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: createChildRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/child',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(createChildRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete One Child
         * @summary Delete One Child
         * @param {string} id Resource Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteChild: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteChild', 'id', id)
            const localVarPath = `/child/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/child/{id}',
                httpMethod: 'DELETE'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Many Children
         * @summary Get Many Children
         * @param {Array<'id' | 'employeeId' | 'name' | 'birthdate'>} [select] Select Child fields, comma-separated. (e.g. &#x60;select&#x3D;id,firstName,lastName,workEmail&#x60;)
         * @param {ChildGetManyFiltersParameter} [filters] Filters conditions per field. (e.g. &#x60;filters[id][$eq]&#x3D;507f1f77bcf86cd799439011&#x60;)
         * @param {number} [limit] Limit amount of received Children. (e.g. &#x60;limit&#x3D;20&#x60;)
         * @param {number} [offset] Offset amount of received Children. (e.g. &#x60;offset&#x3D;20&#x60;)
         * @param {ChildGetManySortParameter} [sort] Sort received Children by field. (e.g. &#x60;sort[id]&#x3D;asc&#x60;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMany: async (select?: Array<'id' | 'employeeId' | 'name' | 'birthdate'>, filters?: ChildGetManyFiltersParameter, limit?: number, offset?: number, sort?: ChildGetManySortParameter, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/child`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (select) {
                localVarQueryParameter['select'] = select.join(COLLECTION_FORMATS.csv);
            }

            if (filters !== undefined) {
                localVarQueryParameter['filters'] = filters;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/child',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get One Child
         * @summary Get One Child
         * @param {string} id Resource Id
         * @param {Array<'id' | 'employeeId' | 'name' | 'birthdate'>} [select] Select Child fields, comma-separated. (e.g. &#x60;select&#x3D;id,firstName,lastName,workEmail&#x60;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOneChild: async (id: string, select?: Array<'id' | 'employeeId' | 'name' | 'birthdate'>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getOneChild', 'id', id)
            const localVarPath = `/child/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (select) {
                localVarQueryParameter['select'] = select.join(COLLECTION_FORMATS.csv);
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/child/{id}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Replace One Child
         * @summary Replace One Child
         * @param {string} id Resource Id
         * @param {UpdateChildRequest} updateChildRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        replaceChildData: async (id: string, updateChildRequest: UpdateChildRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('replaceChildData', 'id', id)
            // verify required parameter 'updateChildRequest' is not null or undefined
            assertParamExists('replaceChildData', 'updateChildRequest', updateChildRequest)
            const localVarPath = `/child/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: updateChildRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/child/{id}',
                httpMethod: 'PUT'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(updateChildRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update One Child
         * @summary Update One Child
         * @param {string} id Resource Id
         * @param {UpdateChildRequest} updateChildRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateChildData: async (id: string, updateChildRequest: UpdateChildRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateChildData', 'id', id)
            // verify required parameter 'updateChildRequest' is not null or undefined
            assertParamExists('updateChildData', 'updateChildRequest', updateChildRequest)
            const localVarPath = `/child/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: updateChildRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/child/{id}',
                httpMethod: 'PATCH'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(updateChildRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ChildApi - functional programming interface
 * @export
 */
export const ChildApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ChildApiAxiosParamCreator(configuration)
    return {
        /**
         * Create One Child
         * @summary Create One Child
         * @param {ChildApiCreateOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOne(requestParameters: ChildApiCreateOneRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChildResponseMapped>> {
            const createChildRequest: CreateChildRequest = {
                employeeId: requestParameters.employeeId,
                name: requestParameters.name,
                birthdate: requestParameters.birthdate
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOne(createChildRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Delete One Child
         * @summary Delete One Child
         * @param {ChildApiDeleteChildRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteChild(requestParameters: ChildApiDeleteChildRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmptyResponseMapped>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteChild(requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get Many Children
         * @summary Get Many Children
         * @param {ChildApiGetManyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMany(requestParameters: ChildApiGetManyRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChildrenGetManyResponseMapped>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMany(requestParameters.select, requestParameters.filters, requestParameters.limit, requestParameters.offset, requestParameters.sort, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get One Child
         * @summary Get One Child
         * @param {ChildApiGetOneChildRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOneChild(requestParameters: ChildApiGetOneChildRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChildGetOneResponseMapped>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOneChild(requestParameters.id, requestParameters.select, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Replace One Child
         * @summary Replace One Child
         * @param {ChildApiReplaceChildDataRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async replaceChildData(requestParameters: ChildApiReplaceChildDataRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChildResponseMapped>> {
            const updateChildRequest: UpdateChildRequest = {
                name: requestParameters.name,
                birthdate: requestParameters.birthdate
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.replaceChildData(requestParameters.id, updateChildRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Update One Child
         * @summary Update One Child
         * @param {ChildApiUpdateChildDataRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateChildData(requestParameters: ChildApiUpdateChildDataRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChildResponseMapped>> {
            const updateChildRequest: UpdateChildRequest = {
                name: requestParameters.name,
                birthdate: requestParameters.birthdate
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateChildData(requestParameters.id, updateChildRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ChildApi - factory interface
 * @export
 */
export const ChildApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ChildApiFp(configuration)
    return {
        /**
         * Create One Child
         * @summary Create One Child
         * @param {ChildApiCreateOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOne(requestParameters: ChildApiCreateOneRequest, options?: AxiosRequestConfig): AxiosPromise<ChildResponseMapped> {
            return localVarFp.createOne(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete One Child
         * @summary Delete One Child
         * @param {ChildApiDeleteChildRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteChild(requestParameters: ChildApiDeleteChildRequest, options?: AxiosRequestConfig): AxiosPromise<EmptyResponseMapped> {
            return localVarFp.deleteChild(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Get Many Children
         * @summary Get Many Children
         * @param {ChildApiGetManyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMany(requestParameters: ChildApiGetManyRequest, options?: AxiosRequestConfig): AxiosPromise<ChildrenGetManyResponseMapped> {
            return localVarFp.getMany(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Get One Child
         * @summary Get One Child
         * @param {ChildApiGetOneChildRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOneChild(requestParameters: ChildApiGetOneChildRequest, options?: AxiosRequestConfig): AxiosPromise<ChildGetOneResponseMapped> {
            return localVarFp.getOneChild(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Replace One Child
         * @summary Replace One Child
         * @param {ChildApiReplaceChildDataRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        replaceChildData(requestParameters: ChildApiReplaceChildDataRequest, options?: AxiosRequestConfig): AxiosPromise<ChildResponseMapped> {
            return localVarFp.replaceChildData(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Update One Child
         * @summary Update One Child
         * @param {ChildApiUpdateChildDataRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateChildData(requestParameters: ChildApiUpdateChildDataRequest, options?: AxiosRequestConfig): AxiosPromise<ChildResponseMapped> {
            return localVarFp.updateChildData(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createOne operation in ChildApi.
 * @export
 * @interface ChildApiCreateOneRequest
 */
export type ChildApiCreateOneRequest = {
    
} & CreateChildRequest

/**
 * Request parameters for deleteChild operation in ChildApi.
 * @export
 * @interface ChildApiDeleteChildRequest
 */
export type ChildApiDeleteChildRequest = {
    
    /**
    * Resource Id
    * @type {string}
    * @memberof ChildApiDeleteChild
    */
    readonly id: string
    
}

/**
 * Request parameters for getMany operation in ChildApi.
 * @export
 * @interface ChildApiGetManyRequest
 */
export type ChildApiGetManyRequest = {
    
    /**
    * Select Child fields, comma-separated. (e.g. `select=id,firstName,lastName,workEmail`)
    * @type {Array<'id' | 'employeeId' | 'name' | 'birthdate'>}
    * @memberof ChildApiGetMany
    */
    readonly select?: Array<'id' | 'employeeId' | 'name' | 'birthdate'>
    
    /**
    * Filters conditions per field. (e.g. `filters[id][$eq]=507f1f77bcf86cd799439011`)
    * @type {ChildGetManyFiltersParameter}
    * @memberof ChildApiGetMany
    */
    readonly filters?: ChildGetManyFiltersParameter
    
    /**
    * Limit amount of received Children. (e.g. `limit=20`)
    * @type {number}
    * @memberof ChildApiGetMany
    */
    readonly limit?: number
    
    /**
    * Offset amount of received Children. (e.g. `offset=20`)
    * @type {number}
    * @memberof ChildApiGetMany
    */
    readonly offset?: number
    
    /**
    * Sort received Children by field. (e.g. `sort[id]=asc`)
    * @type {ChildGetManySortParameter}
    * @memberof ChildApiGetMany
    */
    readonly sort?: ChildGetManySortParameter
    
}

/**
 * Request parameters for getOneChild operation in ChildApi.
 * @export
 * @interface ChildApiGetOneChildRequest
 */
export type ChildApiGetOneChildRequest = {
    
    /**
    * Resource Id
    * @type {string}
    * @memberof ChildApiGetOneChild
    */
    readonly id: string
    
    /**
    * Select Child fields, comma-separated. (e.g. `select=id,firstName,lastName,workEmail`)
    * @type {Array<'id' | 'employeeId' | 'name' | 'birthdate'>}
    * @memberof ChildApiGetOneChild
    */
    readonly select?: Array<'id' | 'employeeId' | 'name' | 'birthdate'>
    
}

/**
 * Request parameters for replaceChildData operation in ChildApi.
 * @export
 * @interface ChildApiReplaceChildDataRequest
 */
export type ChildApiReplaceChildDataRequest = {
    
    /**
    * Resource Id
    * @type {string}
    * @memberof ChildApiReplaceChildData
    */
    readonly id: string
    
} & UpdateChildRequest

/**
 * Request parameters for updateChildData operation in ChildApi.
 * @export
 * @interface ChildApiUpdateChildDataRequest
 */
export type ChildApiUpdateChildDataRequest = {
    
    /**
    * Resource Id
    * @type {string}
    * @memberof ChildApiUpdateChildData
    */
    readonly id: string
    
} & UpdateChildRequest

/**
 * ChildApiGenerated - object-oriented interface
 * @export
 * @class ChildApiGenerated
 * @extends {BaseAPI}
 */
export class ChildApiGenerated extends BaseAPI {
    /**
     * Create One Child
     * @summary Create One Child
     * @param {ChildApiCreateOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChildApiGenerated
     */
    public createOne(requestParameters: ChildApiCreateOneRequest, options?: AxiosRequestConfig) {
        return ChildApiFp(this.configuration).createOne(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete One Child
     * @summary Delete One Child
     * @param {ChildApiDeleteChildRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChildApiGenerated
     */
    public deleteChild(requestParameters: ChildApiDeleteChildRequest, options?: AxiosRequestConfig) {
        return ChildApiFp(this.configuration).deleteChild(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get Many Children
     * @summary Get Many Children
     * @param {ChildApiGetManyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChildApiGenerated
     */
    public getMany(requestParameters: ChildApiGetManyRequest, options?: AxiosRequestConfig) {
        return ChildApiFp(this.configuration).getMany(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get One Child
     * @summary Get One Child
     * @param {ChildApiGetOneChildRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChildApiGenerated
     */
    public getOneChild(requestParameters: ChildApiGetOneChildRequest, options?: AxiosRequestConfig) {
        return ChildApiFp(this.configuration).getOneChild(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Replace One Child
     * @summary Replace One Child
     * @param {ChildApiReplaceChildDataRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChildApiGenerated
     */
    public replaceChildData(requestParameters: ChildApiReplaceChildDataRequest, options?: AxiosRequestConfig) {
        return ChildApiFp(this.configuration).replaceChildData(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update One Child
     * @summary Update One Child
     * @param {ChildApiUpdateChildDataRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChildApiGenerated
     */
    public updateChildData(requestParameters: ChildApiUpdateChildDataRequest, options?: AxiosRequestConfig) {
        return ChildApiFp(this.configuration).updateChildData(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
