/* tslint:disable */
/* eslint-disable */
/*
AlexisHR API

<h1 id=\"introduction\">Introduction</h1>
<p>
  AlexisHR API is currently in preview. This means that small, backward
  incompatible changes might be introduced while in preview. The changes will be
  documented and communicated.
  <a
    href=\"https://cdn.forms-content.sg-form.com/56c6a65c-90a2-11eb-a700-a6de1aea3a1a\"
    target=\"_blank\"
    ><button>Subscribe to updates</button></a
  >
</p>

<h1 id=\"authentication\">Authentication</h1>
<pre class=\"click-to-expand-wrapper is-snippet-wrapper language-undefined\">
<code class=\"is-highlighted language-bash\">curl https://api.alexishr.com/v1/employee \\
  -H \"Authorization: Bearer &lt;your_access_token&gt;\"</code>
</pre>
<p>
  Authenticate your account when using the API by including your secret Access
  Token in the request.
  <a href=\"https://app.alexishr.com/access-tokens\">Manage your Access Tokens</a
  >.
</p>
<p>
  Authentication is performed by passing the Access Token in the Authorization
  header.
</p>
<hr />

<h1 id=\"structure\">Structure</h1>
<p>
  You will find the structure of the API to be highly uniform and consistent.
  Typically every resource can be accessed via a top level endpoint, such as
  <code>/v1/employee</code>. For every such resource, you can perform some of
  the following operations:
</p>
<h2>Operations</h2>
<table>
  <tr>
    <td>GET /v1/:resource</td>
    <td>List all objects of this type</td>
  </tr>
  <tr>
    <td>GET /v1/:resource/:id</td>
    <td>Retrieve a resource by id</td>
  </tr>
  <tr>
    <td>POST /v1/:resource</td>
    <td>Create a resource of this type</td>
  </tr>
  <tr>
    <td>PATCH /v1/:resource/:id</td>
    <td>Update the resource by id</td>
  </tr>
  <tr>
    <td>DELETE /v1/:resource/:id</td>
    <td>Delete the resource by id</td>
  </tr>
</table>
<hr />

<h1 id=\"roles\">Roles</h1>
<p>The Access Tokens will have owner permission on the account</p>
<hr />

<h1 id=\"filters\">Filters</h1>
<p>
  Some of the list endpoints allow to filter results by certain conditions.
  Refer to specific resources to find out what criteria are allowed. Below is a
  list of the different conditions.
</p>

<h4 id=\"eq\"><code>$eq</code></h4>
<p>Find all results matching the attribute value specified.</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[fieldName][$eq]=value</code></pre>
</div>
<p>Can also be simplified like this.</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[fieldName]=value</code></pre>
</div>

<h4 id=\"neq\"><code>$neq</code></h4>
<p>Find all results not matching the attribute value specified.</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[fieldName][$neq]=value</code></pre>
</div>

<h4 id=\"gt\"><code>$gt</code>, <code>$gte</code></h4>
<p>
  Find all results where the value is more (<code>$gt</code>) or more and equal
  (<code>$gte</code>) to a given value.
</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[startDate][$gte]=2020-01-01</code></pre>
</div>
<hr />

<h4 id=\"lt\"><code>$lt</code>, <code>$lte</code></h4>
<p>
  Find all results where the value is less (<code>$lt</code>) or less and equal
  (<code>$lte</code>) to a given value.
</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[startDate][$lte]=2020-01-01</code></pre>
</div>
<hr />

<h4 id=\"in\"><code>$in</code>, <code>$nin</code></h4>
<p>
  Find all results matching (<code>$in</code>) or not matching
  (<code>$nin</code>) any of the attribute values specified.
</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[fieldName][$in][]=value1&filters[fieldName][$in][]=value2</code></pre>
</div>
<hr />

<h4 id=\"between\"><code>$between</code></h4>
<p>Find all results between two values specified.</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[startDate][$between][]=2020-01-01&filters[startDate][$between][]=2020-12-31</code></pre>
</div>
<hr />

<h1 id=\"versioning\">Versioning</h1>
<p>
  Each version of the API is guaranteed to be compatible with the resources of
  the same version. When we make breaking changes to the API a new version will
  be published
</p>
<hr />

<h1 id=\"changelog\">Changelog</h1>
<h3>2023-12-20</h3>
<p>Field [updated] added for filter & select for Get Many Employments and Get Many Employees.</p>
<h3>2021-03-15</h3>
<p>First draft was published</p>
<hr />

# Authentication

<!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: v1-preview
Contact: support@alexishr.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BadRequestResponse } from '../models';
// @ts-ignore
import { CreateDepartmentRequest } from '../models';
// @ts-ignore
import { DepartmentGetOneResponseMapped } from '../models';
// @ts-ignore
import { DepartmentListManyDepartmentsFiltersParameter } from '../models';
// @ts-ignore
import { DepartmentListManyDepartmentsSortParameter } from '../models';
// @ts-ignore
import { DepartmentResponseMapped } from '../models';
// @ts-ignore
import { DepartmentsGetManyResponseMapped } from '../models';
// @ts-ignore
import { EmptyResponseMapped } from '../models';
// @ts-ignore
import { ForbiddenResponse } from '../models';
// @ts-ignore
import { InternalServerErrorResponse } from '../models';
// @ts-ignore
import { NotFoundResponse } from '../models';
// @ts-ignore
import { UnauthorizedResponse } from '../models';
// @ts-ignore
import { UpdateDepartmentRequest } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * DepartmentApi - axios parameter creator
 * @export
 */
export const DepartmentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create One Department
         * @summary Create One Department
         * @param {CreateDepartmentRequest} createDepartmentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOne: async (createDepartmentRequest: CreateDepartmentRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createDepartmentRequest' is not null or undefined
            assertParamExists('createOne', 'createDepartmentRequest', createDepartmentRequest)
            const localVarPath = `/department`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: createDepartmentRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/department',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(createDepartmentRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete One Department
         * @summary Delete One Department
         * @param {string} id Resource Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOneDepartment: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteOneDepartment', 'id', id)
            const localVarPath = `/department/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/department/{id}',
                httpMethod: 'DELETE'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get One Department
         * @summary Get One Department
         * @param {string} id Resource Id
         * @param {Array<'id' | 'companyId' | 'name' | 'costCenterId' | 'effectiveCostCenterId' | 'parentId'>} [select] Select Department fields, comma-separated. (e.g. &#x60;select&#x3D;id,firstName,lastName,workEmail&#x60;)
         * @param {Array<'costCenter' | 'effectiveCostCenter'>} [relations] Select related Department resources, comma-separated. (e.g. &#x60;relations&#x3D;office,department&#x60;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOne: async (id: string, select?: Array<'id' | 'companyId' | 'name' | 'costCenterId' | 'effectiveCostCenterId' | 'parentId'>, relations?: Array<'costCenter' | 'effectiveCostCenter'>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getOne', 'id', id)
            const localVarPath = `/department/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (select) {
                localVarQueryParameter['select'] = select.join(COLLECTION_FORMATS.csv);
            }

            if (relations) {
                localVarQueryParameter['relations'] = relations.join(COLLECTION_FORMATS.csv);
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/department/{id}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Many Departments
         * @summary Get Many Departments
         * @param {Array<'id' | 'companyId' | 'name' | 'costCenterId' | 'effectiveCostCenterId' | 'parentId'>} [select] Select Department fields, comma-separated. (e.g. &#x60;select&#x3D;id,firstName,lastName,workEmail&#x60;)
         * @param {Array<'costCenter' | 'effectiveCostCenter'>} [relations] Select related Department resources, comma-separated. (e.g. &#x60;relations&#x3D;office,department&#x60;)
         * @param {DepartmentListManyDepartmentsFiltersParameter} [filters] Filters conditions per field. (e.g. &#x60;filters[id][$eq]&#x3D;507f1f77bcf86cd799439011&#x60;)
         * @param {number} [limit] Limit amount of received Departments. (e.g. &#x60;limit&#x3D;20&#x60;)
         * @param {number} [offset] Offset amount of received Departments. (e.g. &#x60;offset&#x3D;20&#x60;)
         * @param {DepartmentListManyDepartmentsSortParameter} [sort] Sort received Departments by field. (e.g. &#x60;sort[id]&#x3D;asc&#x60;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listManyDepartments: async (select?: Array<'id' | 'companyId' | 'name' | 'costCenterId' | 'effectiveCostCenterId' | 'parentId'>, relations?: Array<'costCenter' | 'effectiveCostCenter'>, filters?: DepartmentListManyDepartmentsFiltersParameter, limit?: number, offset?: number, sort?: DepartmentListManyDepartmentsSortParameter, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/department`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (select) {
                localVarQueryParameter['select'] = select.join(COLLECTION_FORMATS.csv);
            }

            if (relations) {
                localVarQueryParameter['relations'] = relations.join(COLLECTION_FORMATS.csv);
            }

            if (filters !== undefined) {
                localVarQueryParameter['filters'] = filters;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/department',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Replace One Department
         * @summary Replace One Department
         * @param {string} id Resource Id
         * @param {UpdateDepartmentRequest} updateDepartmentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        replaceOne: async (id: string, updateDepartmentRequest: UpdateDepartmentRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('replaceOne', 'id', id)
            // verify required parameter 'updateDepartmentRequest' is not null or undefined
            assertParamExists('replaceOne', 'updateDepartmentRequest', updateDepartmentRequest)
            const localVarPath = `/department/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: updateDepartmentRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/department/{id}',
                httpMethod: 'PUT'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(updateDepartmentRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update One Department
         * @summary Update One Department
         * @param {string} id Resource Id
         * @param {UpdateDepartmentRequest} updateDepartmentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOneDepartment: async (id: string, updateDepartmentRequest: UpdateDepartmentRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateOneDepartment', 'id', id)
            // verify required parameter 'updateDepartmentRequest' is not null or undefined
            assertParamExists('updateOneDepartment', 'updateDepartmentRequest', updateDepartmentRequest)
            const localVarPath = `/department/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: updateDepartmentRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/department/{id}',
                httpMethod: 'PATCH'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(updateDepartmentRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DepartmentApi - functional programming interface
 * @export
 */
export const DepartmentApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DepartmentApiAxiosParamCreator(configuration)
    return {
        /**
         * Create One Department
         * @summary Create One Department
         * @param {DepartmentApiCreateOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOne(requestParameters: DepartmentApiCreateOneRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DepartmentResponseMapped>> {
            const createDepartmentRequest: CreateDepartmentRequest = {
                description: requestParameters.description,
                name: requestParameters.name,
                costCenterId: requestParameters.costCenterId,
                parentId: requestParameters.parentId
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOne(createDepartmentRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Delete One Department
         * @summary Delete One Department
         * @param {DepartmentApiDeleteOneDepartmentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteOneDepartment(requestParameters: DepartmentApiDeleteOneDepartmentRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmptyResponseMapped>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteOneDepartment(requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get One Department
         * @summary Get One Department
         * @param {DepartmentApiGetOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOne(requestParameters: DepartmentApiGetOneRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DepartmentGetOneResponseMapped>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOne(requestParameters.id, requestParameters.select, requestParameters.relations, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get Many Departments
         * @summary Get Many Departments
         * @param {DepartmentApiListManyDepartmentsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listManyDepartments(requestParameters: DepartmentApiListManyDepartmentsRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DepartmentsGetManyResponseMapped>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listManyDepartments(requestParameters.select, requestParameters.relations, requestParameters.filters, requestParameters.limit, requestParameters.offset, requestParameters.sort, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Replace One Department
         * @summary Replace One Department
         * @param {DepartmentApiReplaceOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async replaceOne(requestParameters: DepartmentApiReplaceOneRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DepartmentResponseMapped>> {
            const updateDepartmentRequest: UpdateDepartmentRequest = {
                description: requestParameters.description,
                name: requestParameters.name,
                costCenterId: requestParameters.costCenterId,
                parentId: requestParameters.parentId
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.replaceOne(requestParameters.id, updateDepartmentRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Update One Department
         * @summary Update One Department
         * @param {DepartmentApiUpdateOneDepartmentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateOneDepartment(requestParameters: DepartmentApiUpdateOneDepartmentRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DepartmentResponseMapped>> {
            const updateDepartmentRequest: UpdateDepartmentRequest = {
                description: requestParameters.description,
                name: requestParameters.name,
                costCenterId: requestParameters.costCenterId,
                parentId: requestParameters.parentId
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateOneDepartment(requestParameters.id, updateDepartmentRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DepartmentApi - factory interface
 * @export
 */
export const DepartmentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DepartmentApiFp(configuration)
    return {
        /**
         * Create One Department
         * @summary Create One Department
         * @param {DepartmentApiCreateOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOne(requestParameters: DepartmentApiCreateOneRequest, options?: AxiosRequestConfig): AxiosPromise<DepartmentResponseMapped> {
            return localVarFp.createOne(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete One Department
         * @summary Delete One Department
         * @param {DepartmentApiDeleteOneDepartmentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOneDepartment(requestParameters: DepartmentApiDeleteOneDepartmentRequest, options?: AxiosRequestConfig): AxiosPromise<EmptyResponseMapped> {
            return localVarFp.deleteOneDepartment(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Get One Department
         * @summary Get One Department
         * @param {DepartmentApiGetOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOne(requestParameters: DepartmentApiGetOneRequest, options?: AxiosRequestConfig): AxiosPromise<DepartmentGetOneResponseMapped> {
            return localVarFp.getOne(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Get Many Departments
         * @summary Get Many Departments
         * @param {DepartmentApiListManyDepartmentsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listManyDepartments(requestParameters: DepartmentApiListManyDepartmentsRequest, options?: AxiosRequestConfig): AxiosPromise<DepartmentsGetManyResponseMapped> {
            return localVarFp.listManyDepartments(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Replace One Department
         * @summary Replace One Department
         * @param {DepartmentApiReplaceOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        replaceOne(requestParameters: DepartmentApiReplaceOneRequest, options?: AxiosRequestConfig): AxiosPromise<DepartmentResponseMapped> {
            return localVarFp.replaceOne(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Update One Department
         * @summary Update One Department
         * @param {DepartmentApiUpdateOneDepartmentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOneDepartment(requestParameters: DepartmentApiUpdateOneDepartmentRequest, options?: AxiosRequestConfig): AxiosPromise<DepartmentResponseMapped> {
            return localVarFp.updateOneDepartment(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createOne operation in DepartmentApi.
 * @export
 * @interface DepartmentApiCreateOneRequest
 */
export type DepartmentApiCreateOneRequest = {
    
} & CreateDepartmentRequest

/**
 * Request parameters for deleteOneDepartment operation in DepartmentApi.
 * @export
 * @interface DepartmentApiDeleteOneDepartmentRequest
 */
export type DepartmentApiDeleteOneDepartmentRequest = {
    
    /**
    * Resource Id
    * @type {string}
    * @memberof DepartmentApiDeleteOneDepartment
    */
    readonly id: string
    
}

/**
 * Request parameters for getOne operation in DepartmentApi.
 * @export
 * @interface DepartmentApiGetOneRequest
 */
export type DepartmentApiGetOneRequest = {
    
    /**
    * Resource Id
    * @type {string}
    * @memberof DepartmentApiGetOne
    */
    readonly id: string
    
    /**
    * Select Department fields, comma-separated. (e.g. `select=id,firstName,lastName,workEmail`)
    * @type {Array<'id' | 'companyId' | 'name' | 'costCenterId' | 'effectiveCostCenterId' | 'parentId'>}
    * @memberof DepartmentApiGetOne
    */
    readonly select?: Array<'id' | 'companyId' | 'name' | 'costCenterId' | 'effectiveCostCenterId' | 'parentId'>
    
    /**
    * Select related Department resources, comma-separated. (e.g. `relations=office,department`)
    * @type {Array<'costCenter' | 'effectiveCostCenter'>}
    * @memberof DepartmentApiGetOne
    */
    readonly relations?: Array<'costCenter' | 'effectiveCostCenter'>
    
}

/**
 * Request parameters for listManyDepartments operation in DepartmentApi.
 * @export
 * @interface DepartmentApiListManyDepartmentsRequest
 */
export type DepartmentApiListManyDepartmentsRequest = {
    
    /**
    * Select Department fields, comma-separated. (e.g. `select=id,firstName,lastName,workEmail`)
    * @type {Array<'id' | 'companyId' | 'name' | 'costCenterId' | 'effectiveCostCenterId' | 'parentId'>}
    * @memberof DepartmentApiListManyDepartments
    */
    readonly select?: Array<'id' | 'companyId' | 'name' | 'costCenterId' | 'effectiveCostCenterId' | 'parentId'>
    
    /**
    * Select related Department resources, comma-separated. (e.g. `relations=office,department`)
    * @type {Array<'costCenter' | 'effectiveCostCenter'>}
    * @memberof DepartmentApiListManyDepartments
    */
    readonly relations?: Array<'costCenter' | 'effectiveCostCenter'>
    
    /**
    * Filters conditions per field. (e.g. `filters[id][$eq]=507f1f77bcf86cd799439011`)
    * @type {DepartmentListManyDepartmentsFiltersParameter}
    * @memberof DepartmentApiListManyDepartments
    */
    readonly filters?: DepartmentListManyDepartmentsFiltersParameter
    
    /**
    * Limit amount of received Departments. (e.g. `limit=20`)
    * @type {number}
    * @memberof DepartmentApiListManyDepartments
    */
    readonly limit?: number
    
    /**
    * Offset amount of received Departments. (e.g. `offset=20`)
    * @type {number}
    * @memberof DepartmentApiListManyDepartments
    */
    readonly offset?: number
    
    /**
    * Sort received Departments by field. (e.g. `sort[id]=asc`)
    * @type {DepartmentListManyDepartmentsSortParameter}
    * @memberof DepartmentApiListManyDepartments
    */
    readonly sort?: DepartmentListManyDepartmentsSortParameter
    
}

/**
 * Request parameters for replaceOne operation in DepartmentApi.
 * @export
 * @interface DepartmentApiReplaceOneRequest
 */
export type DepartmentApiReplaceOneRequest = {
    
    /**
    * Resource Id
    * @type {string}
    * @memberof DepartmentApiReplaceOne
    */
    readonly id: string
    
} & UpdateDepartmentRequest

/**
 * Request parameters for updateOneDepartment operation in DepartmentApi.
 * @export
 * @interface DepartmentApiUpdateOneDepartmentRequest
 */
export type DepartmentApiUpdateOneDepartmentRequest = {
    
    /**
    * Resource Id
    * @type {string}
    * @memberof DepartmentApiUpdateOneDepartment
    */
    readonly id: string
    
} & UpdateDepartmentRequest

/**
 * DepartmentApiGenerated - object-oriented interface
 * @export
 * @class DepartmentApiGenerated
 * @extends {BaseAPI}
 */
export class DepartmentApiGenerated extends BaseAPI {
    /**
     * Create One Department
     * @summary Create One Department
     * @param {DepartmentApiCreateOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DepartmentApiGenerated
     */
    public createOne(requestParameters: DepartmentApiCreateOneRequest, options?: AxiosRequestConfig) {
        return DepartmentApiFp(this.configuration).createOne(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete One Department
     * @summary Delete One Department
     * @param {DepartmentApiDeleteOneDepartmentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DepartmentApiGenerated
     */
    public deleteOneDepartment(requestParameters: DepartmentApiDeleteOneDepartmentRequest, options?: AxiosRequestConfig) {
        return DepartmentApiFp(this.configuration).deleteOneDepartment(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get One Department
     * @summary Get One Department
     * @param {DepartmentApiGetOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DepartmentApiGenerated
     */
    public getOne(requestParameters: DepartmentApiGetOneRequest, options?: AxiosRequestConfig) {
        return DepartmentApiFp(this.configuration).getOne(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get Many Departments
     * @summary Get Many Departments
     * @param {DepartmentApiListManyDepartmentsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DepartmentApiGenerated
     */
    public listManyDepartments(requestParameters: DepartmentApiListManyDepartmentsRequest, options?: AxiosRequestConfig) {
        return DepartmentApiFp(this.configuration).listManyDepartments(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Replace One Department
     * @summary Replace One Department
     * @param {DepartmentApiReplaceOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DepartmentApiGenerated
     */
    public replaceOne(requestParameters: DepartmentApiReplaceOneRequest, options?: AxiosRequestConfig) {
        return DepartmentApiFp(this.configuration).replaceOne(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update One Department
     * @summary Update One Department
     * @param {DepartmentApiUpdateOneDepartmentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DepartmentApiGenerated
     */
    public updateOneDepartment(requestParameters: DepartmentApiUpdateOneDepartmentRequest, options?: AxiosRequestConfig) {
        return DepartmentApiFp(this.configuration).updateOneDepartment(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
