/* tslint:disable */
/* eslint-disable */
/*
AlexisHR API

<h1 id=\"introduction\">Introduction</h1>
<p>
  AlexisHR API is currently in preview. This means that small, backward
  incompatible changes might be introduced while in preview. The changes will be
  documented and communicated.
  <a
    href=\"https://cdn.forms-content.sg-form.com/56c6a65c-90a2-11eb-a700-a6de1aea3a1a\"
    target=\"_blank\"
    ><button>Subscribe to updates</button></a
  >
</p>

<h1 id=\"authentication\">Authentication</h1>
<pre class=\"click-to-expand-wrapper is-snippet-wrapper language-undefined\">
<code class=\"is-highlighted language-bash\">curl https://api.alexishr.com/v1/employee \\
  -H \"Authorization: Bearer &lt;your_access_token&gt;\"</code>
</pre>
<p>
  Authenticate your account when using the API by including your secret Access
  Token in the request.
  <a href=\"https://app.alexishr.com/access-tokens\">Manage your Access Tokens</a
  >.
</p>
<p>
  Authentication is performed by passing the Access Token in the Authorization
  header.
</p>
<hr />

<h1 id=\"structure\">Structure</h1>
<p>
  You will find the structure of the API to be highly uniform and consistent.
  Typically every resource can be accessed via a top level endpoint, such as
  <code>/v1/employee</code>. For every such resource, you can perform some of
  the following operations:
</p>
<h2>Operations</h2>
<table>
  <tr>
    <td>GET /v1/:resource</td>
    <td>List all objects of this type</td>
  </tr>
  <tr>
    <td>GET /v1/:resource/:id</td>
    <td>Retrieve a resource by id</td>
  </tr>
  <tr>
    <td>POST /v1/:resource</td>
    <td>Create a resource of this type</td>
  </tr>
  <tr>
    <td>PATCH /v1/:resource/:id</td>
    <td>Update the resource by id</td>
  </tr>
  <tr>
    <td>DELETE /v1/:resource/:id</td>
    <td>Delete the resource by id</td>
  </tr>
</table>
<hr />

<h1 id=\"roles\">Roles</h1>
<p>The Access Tokens will have owner permission on the account</p>
<hr />

<h1 id=\"filters\">Filters</h1>
<p>
  Some of the list endpoints allow to filter results by certain conditions.
  Refer to specific resources to find out what criteria are allowed. Below is a
  list of the different conditions.
</p>

<h4 id=\"eq\"><code>$eq</code></h4>
<p>Find all results matching the attribute value specified.</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[fieldName][$eq]=value</code></pre>
</div>
<p>Can also be simplified like this.</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[fieldName]=value</code></pre>
</div>

<h4 id=\"neq\"><code>$neq</code></h4>
<p>Find all results not matching the attribute value specified.</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[fieldName][$neq]=value</code></pre>
</div>

<h4 id=\"gt\"><code>$gt</code>, <code>$gte</code></h4>
<p>
  Find all results where the value is more (<code>$gt</code>) or more and equal
  (<code>$gte</code>) to a given value.
</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[startDate][$gte]=2020-01-01</code></pre>
</div>
<hr />

<h4 id=\"lt\"><code>$lt</code>, <code>$lte</code></h4>
<p>
  Find all results where the value is less (<code>$lt</code>) or less and equal
  (<code>$lte</code>) to a given value.
</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[startDate][$lte]=2020-01-01</code></pre>
</div>
<hr />

<h4 id=\"in\"><code>$in</code>, <code>$nin</code></h4>
<p>
  Find all results matching (<code>$in</code>) or not matching
  (<code>$nin</code>) any of the attribute values specified.
</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[fieldName][$in][]=value1&filters[fieldName][$in][]=value2</code></pre>
</div>
<hr />

<h4 id=\"between\"><code>$between</code></h4>
<p>Find all results between two values specified.</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[startDate][$between][]=2020-01-01&filters[startDate][$between][]=2020-12-31</code></pre>
</div>
<hr />

<h1 id=\"versioning\">Versioning</h1>
<p>
  Each version of the API is guaranteed to be compatible with the resources of
  the same version. When we make breaking changes to the API a new version will
  be published
</p>
<hr />

<h1 id=\"changelog\">Changelog</h1>
<h3>2023-12-20</h3>
<p>Field [updated] added for filter & select for Get Many Employments and Get Many Employees.</p>
<h3>2021-03-15</h3>
<p>First draft was published</p>
<hr />

# Authentication

<!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: v1-preview
Contact: support@alexishr.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BadRequestResponse } from '../models';
// @ts-ignore
import { CreateOfficeRequest } from '../models';
// @ts-ignore
import { EmptyResponseMapped } from '../models';
// @ts-ignore
import { ForbiddenResponse } from '../models';
// @ts-ignore
import { InternalServerErrorResponse } from '../models';
// @ts-ignore
import { NotFoundResponse } from '../models';
// @ts-ignore
import { OfficeGetOneResponseMapped } from '../models';
// @ts-ignore
import { OfficeListManyOfficesFiltersParameter } from '../models';
// @ts-ignore
import { OfficeListManyOfficesSortParameter } from '../models';
// @ts-ignore
import { OfficeResponseMapped } from '../models';
// @ts-ignore
import { OfficesGetManyResponseMapped } from '../models';
// @ts-ignore
import { UnauthorizedResponse } from '../models';
// @ts-ignore
import { UpdateOfficeRequest } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * OfficeApi - axios parameter creator
 * @export
 */
export const OfficeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create One Office
         * @summary Create One Office
         * @param {CreateOfficeRequest} createOfficeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOneOffice: async (createOfficeRequest: CreateOfficeRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createOfficeRequest' is not null or undefined
            assertParamExists('createOneOffice', 'createOfficeRequest', createOfficeRequest)
            const localVarPath = `/office`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: createOfficeRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/office',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(createOfficeRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete One Office
         * @summary Delete One Office
         * @param {string} id Resource Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOne: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteOne', 'id', id)
            const localVarPath = `/office/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/office/{id}',
                httpMethod: 'DELETE'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get One Office
         * @summary Get One Office
         * @param {string} id Resource Id
         * @param {Array<'id' | 'companyId' | 'name' | 'phone' | 'email' | 'timezone' | 'CFAR' | 'SCB' | 'SNI'>} [select] Select Office fields, comma-separated. (e.g. &#x60;select&#x3D;id,firstName,lastName,workEmail&#x60;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOneOffice: async (id: string, select?: Array<'id' | 'companyId' | 'name' | 'phone' | 'email' | 'timezone' | 'CFAR' | 'SCB' | 'SNI'>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getOneOffice', 'id', id)
            const localVarPath = `/office/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (select) {
                localVarQueryParameter['select'] = select.join(COLLECTION_FORMATS.csv);
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/office/{id}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Many Offices
         * @summary Get Many Offices
         * @param {Array<'id' | 'companyId' | 'name' | 'phone' | 'email' | 'timezone' | 'CFAR' | 'SCB' | 'SNI'>} [select] Select Office fields, comma-separated. (e.g. &#x60;select&#x3D;id,firstName,lastName,workEmail&#x60;)
         * @param {OfficeListManyOfficesFiltersParameter} [filters] Filters conditions per field. (e.g. &#x60;filters[id][$eq]&#x3D;507f1f77bcf86cd799439011&#x60;)
         * @param {number} [limit] Limit amount of received Offices. (e.g. &#x60;limit&#x3D;20&#x60;)
         * @param {number} [offset] Offset amount of received Offices. (e.g. &#x60;offset&#x3D;20&#x60;)
         * @param {OfficeListManyOfficesSortParameter} [sort] Sort received Offices by field. (e.g. &#x60;sort[id]&#x3D;asc&#x60;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listManyOffices: async (select?: Array<'id' | 'companyId' | 'name' | 'phone' | 'email' | 'timezone' | 'CFAR' | 'SCB' | 'SNI'>, filters?: OfficeListManyOfficesFiltersParameter, limit?: number, offset?: number, sort?: OfficeListManyOfficesSortParameter, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/office`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (select) {
                localVarQueryParameter['select'] = select.join(COLLECTION_FORMATS.csv);
            }

            if (filters !== undefined) {
                localVarQueryParameter['filters'] = filters;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/office',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Replace One Office
         * @summary Replace One Office
         * @param {string} id Resource Id
         * @param {UpdateOfficeRequest} updateOfficeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        replaceOne: async (id: string, updateOfficeRequest: UpdateOfficeRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('replaceOne', 'id', id)
            // verify required parameter 'updateOfficeRequest' is not null or undefined
            assertParamExists('replaceOne', 'updateOfficeRequest', updateOfficeRequest)
            const localVarPath = `/office/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: updateOfficeRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/office/{id}',
                httpMethod: 'PUT'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(updateOfficeRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update One Office
         * @summary Update One Office
         * @param {string} id Resource Id
         * @param {UpdateOfficeRequest} updateOfficeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOne: async (id: string, updateOfficeRequest: UpdateOfficeRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateOne', 'id', id)
            // verify required parameter 'updateOfficeRequest' is not null or undefined
            assertParamExists('updateOne', 'updateOfficeRequest', updateOfficeRequest)
            const localVarPath = `/office/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: updateOfficeRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/office/{id}',
                httpMethod: 'PATCH'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(updateOfficeRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OfficeApi - functional programming interface
 * @export
 */
export const OfficeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OfficeApiAxiosParamCreator(configuration)
    return {
        /**
         * Create One Office
         * @summary Create One Office
         * @param {OfficeApiCreateOneOfficeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOneOffice(requestParameters: OfficeApiCreateOneOfficeRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OfficeResponseMapped>> {
            const createOfficeRequest: CreateOfficeRequest = {
                name: requestParameters.name,
                phone: requestParameters.phone,
                email: requestParameters.email,
                timezone: requestParameters.timezone,
                CFAR: requestParameters.CFAR,
                SCB: requestParameters.SCB,
                SNI: requestParameters.SNI
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOneOffice(createOfficeRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Delete One Office
         * @summary Delete One Office
         * @param {OfficeApiDeleteOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteOne(requestParameters: OfficeApiDeleteOneRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmptyResponseMapped>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteOne(requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get One Office
         * @summary Get One Office
         * @param {OfficeApiGetOneOfficeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOneOffice(requestParameters: OfficeApiGetOneOfficeRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OfficeGetOneResponseMapped>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOneOffice(requestParameters.id, requestParameters.select, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get Many Offices
         * @summary Get Many Offices
         * @param {OfficeApiListManyOfficesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listManyOffices(requestParameters: OfficeApiListManyOfficesRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OfficesGetManyResponseMapped>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listManyOffices(requestParameters.select, requestParameters.filters, requestParameters.limit, requestParameters.offset, requestParameters.sort, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Replace One Office
         * @summary Replace One Office
         * @param {OfficeApiReplaceOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async replaceOne(requestParameters: OfficeApiReplaceOneRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OfficeResponseMapped>> {
            const updateOfficeRequest: UpdateOfficeRequest = {
                name: requestParameters.name,
                phone: requestParameters.phone,
                email: requestParameters.email,
                timezone: requestParameters.timezone,
                CFAR: requestParameters.CFAR,
                SCB: requestParameters.SCB,
                SNI: requestParameters.SNI
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.replaceOne(requestParameters.id, updateOfficeRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Update One Office
         * @summary Update One Office
         * @param {OfficeApiUpdateOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateOne(requestParameters: OfficeApiUpdateOneRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OfficeResponseMapped>> {
            const updateOfficeRequest: UpdateOfficeRequest = {
                name: requestParameters.name,
                phone: requestParameters.phone,
                email: requestParameters.email,
                timezone: requestParameters.timezone,
                CFAR: requestParameters.CFAR,
                SCB: requestParameters.SCB,
                SNI: requestParameters.SNI
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateOne(requestParameters.id, updateOfficeRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * OfficeApi - factory interface
 * @export
 */
export const OfficeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OfficeApiFp(configuration)
    return {
        /**
         * Create One Office
         * @summary Create One Office
         * @param {OfficeApiCreateOneOfficeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOneOffice(requestParameters: OfficeApiCreateOneOfficeRequest, options?: AxiosRequestConfig): AxiosPromise<OfficeResponseMapped> {
            return localVarFp.createOneOffice(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete One Office
         * @summary Delete One Office
         * @param {OfficeApiDeleteOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOne(requestParameters: OfficeApiDeleteOneRequest, options?: AxiosRequestConfig): AxiosPromise<EmptyResponseMapped> {
            return localVarFp.deleteOne(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Get One Office
         * @summary Get One Office
         * @param {OfficeApiGetOneOfficeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOneOffice(requestParameters: OfficeApiGetOneOfficeRequest, options?: AxiosRequestConfig): AxiosPromise<OfficeGetOneResponseMapped> {
            return localVarFp.getOneOffice(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Get Many Offices
         * @summary Get Many Offices
         * @param {OfficeApiListManyOfficesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listManyOffices(requestParameters: OfficeApiListManyOfficesRequest, options?: AxiosRequestConfig): AxiosPromise<OfficesGetManyResponseMapped> {
            return localVarFp.listManyOffices(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Replace One Office
         * @summary Replace One Office
         * @param {OfficeApiReplaceOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        replaceOne(requestParameters: OfficeApiReplaceOneRequest, options?: AxiosRequestConfig): AxiosPromise<OfficeResponseMapped> {
            return localVarFp.replaceOne(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Update One Office
         * @summary Update One Office
         * @param {OfficeApiUpdateOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOne(requestParameters: OfficeApiUpdateOneRequest, options?: AxiosRequestConfig): AxiosPromise<OfficeResponseMapped> {
            return localVarFp.updateOne(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createOneOffice operation in OfficeApi.
 * @export
 * @interface OfficeApiCreateOneOfficeRequest
 */
export type OfficeApiCreateOneOfficeRequest = {
    
} & CreateOfficeRequest

/**
 * Request parameters for deleteOne operation in OfficeApi.
 * @export
 * @interface OfficeApiDeleteOneRequest
 */
export type OfficeApiDeleteOneRequest = {
    
    /**
    * Resource Id
    * @type {string}
    * @memberof OfficeApiDeleteOne
    */
    readonly id: string
    
}

/**
 * Request parameters for getOneOffice operation in OfficeApi.
 * @export
 * @interface OfficeApiGetOneOfficeRequest
 */
export type OfficeApiGetOneOfficeRequest = {
    
    /**
    * Resource Id
    * @type {string}
    * @memberof OfficeApiGetOneOffice
    */
    readonly id: string
    
    /**
    * Select Office fields, comma-separated. (e.g. `select=id,firstName,lastName,workEmail`)
    * @type {Array<'id' | 'companyId' | 'name' | 'phone' | 'email' | 'timezone' | 'CFAR' | 'SCB' | 'SNI'>}
    * @memberof OfficeApiGetOneOffice
    */
    readonly select?: Array<'id' | 'companyId' | 'name' | 'phone' | 'email' | 'timezone' | 'CFAR' | 'SCB' | 'SNI'>
    
}

/**
 * Request parameters for listManyOffices operation in OfficeApi.
 * @export
 * @interface OfficeApiListManyOfficesRequest
 */
export type OfficeApiListManyOfficesRequest = {
    
    /**
    * Select Office fields, comma-separated. (e.g. `select=id,firstName,lastName,workEmail`)
    * @type {Array<'id' | 'companyId' | 'name' | 'phone' | 'email' | 'timezone' | 'CFAR' | 'SCB' | 'SNI'>}
    * @memberof OfficeApiListManyOffices
    */
    readonly select?: Array<'id' | 'companyId' | 'name' | 'phone' | 'email' | 'timezone' | 'CFAR' | 'SCB' | 'SNI'>
    
    /**
    * Filters conditions per field. (e.g. `filters[id][$eq]=507f1f77bcf86cd799439011`)
    * @type {OfficeListManyOfficesFiltersParameter}
    * @memberof OfficeApiListManyOffices
    */
    readonly filters?: OfficeListManyOfficesFiltersParameter
    
    /**
    * Limit amount of received Offices. (e.g. `limit=20`)
    * @type {number}
    * @memberof OfficeApiListManyOffices
    */
    readonly limit?: number
    
    /**
    * Offset amount of received Offices. (e.g. `offset=20`)
    * @type {number}
    * @memberof OfficeApiListManyOffices
    */
    readonly offset?: number
    
    /**
    * Sort received Offices by field. (e.g. `sort[id]=asc`)
    * @type {OfficeListManyOfficesSortParameter}
    * @memberof OfficeApiListManyOffices
    */
    readonly sort?: OfficeListManyOfficesSortParameter
    
}

/**
 * Request parameters for replaceOne operation in OfficeApi.
 * @export
 * @interface OfficeApiReplaceOneRequest
 */
export type OfficeApiReplaceOneRequest = {
    
    /**
    * Resource Id
    * @type {string}
    * @memberof OfficeApiReplaceOne
    */
    readonly id: string
    
} & UpdateOfficeRequest

/**
 * Request parameters for updateOne operation in OfficeApi.
 * @export
 * @interface OfficeApiUpdateOneRequest
 */
export type OfficeApiUpdateOneRequest = {
    
    /**
    * Resource Id
    * @type {string}
    * @memberof OfficeApiUpdateOne
    */
    readonly id: string
    
} & UpdateOfficeRequest

/**
 * OfficeApiGenerated - object-oriented interface
 * @export
 * @class OfficeApiGenerated
 * @extends {BaseAPI}
 */
export class OfficeApiGenerated extends BaseAPI {
    /**
     * Create One Office
     * @summary Create One Office
     * @param {OfficeApiCreateOneOfficeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfficeApiGenerated
     */
    public createOneOffice(requestParameters: OfficeApiCreateOneOfficeRequest, options?: AxiosRequestConfig) {
        return OfficeApiFp(this.configuration).createOneOffice(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete One Office
     * @summary Delete One Office
     * @param {OfficeApiDeleteOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfficeApiGenerated
     */
    public deleteOne(requestParameters: OfficeApiDeleteOneRequest, options?: AxiosRequestConfig) {
        return OfficeApiFp(this.configuration).deleteOne(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get One Office
     * @summary Get One Office
     * @param {OfficeApiGetOneOfficeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfficeApiGenerated
     */
    public getOneOffice(requestParameters: OfficeApiGetOneOfficeRequest, options?: AxiosRequestConfig) {
        return OfficeApiFp(this.configuration).getOneOffice(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get Many Offices
     * @summary Get Many Offices
     * @param {OfficeApiListManyOfficesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfficeApiGenerated
     */
    public listManyOffices(requestParameters: OfficeApiListManyOfficesRequest, options?: AxiosRequestConfig) {
        return OfficeApiFp(this.configuration).listManyOffices(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Replace One Office
     * @summary Replace One Office
     * @param {OfficeApiReplaceOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfficeApiGenerated
     */
    public replaceOne(requestParameters: OfficeApiReplaceOneRequest, options?: AxiosRequestConfig) {
        return OfficeApiFp(this.configuration).replaceOne(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update One Office
     * @summary Update One Office
     * @param {OfficeApiUpdateOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfficeApiGenerated
     */
    public updateOne(requestParameters: OfficeApiUpdateOneRequest, options?: AxiosRequestConfig) {
        return OfficeApiFp(this.configuration).updateOne(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
