/* tslint:disable */
/* eslint-disable */
/*
AlexisHR API

<h1 id=\"introduction\">Introduction</h1>
<p>
  AlexisHR API is currently in preview. This means that small, backward
  incompatible changes might be introduced while in preview. The changes will be
  documented and communicated.
  <a
    href=\"https://cdn.forms-content.sg-form.com/56c6a65c-90a2-11eb-a700-a6de1aea3a1a\"
    target=\"_blank\"
    ><button>Subscribe to updates</button></a
  >
</p>

<h1 id=\"authentication\">Authentication</h1>
<pre class=\"click-to-expand-wrapper is-snippet-wrapper language-undefined\">
<code class=\"is-highlighted language-bash\">curl https://api.alexishr.com/v1/employee \\
  -H \"Authorization: Bearer &lt;your_access_token&gt;\"</code>
</pre>
<p>
  Authenticate your account when using the API by including your secret Access
  Token in the request.
  <a href=\"https://app.alexishr.com/access-tokens\">Manage your Access Tokens</a
  >.
</p>
<p>
  Authentication is performed by passing the Access Token in the Authorization
  header.
</p>
<hr />

<h1 id=\"structure\">Structure</h1>
<p>
  You will find the structure of the API to be highly uniform and consistent.
  Typically every resource can be accessed via a top level endpoint, such as
  <code>/v1/employee</code>. For every such resource, you can perform some of
  the following operations:
</p>
<h2>Operations</h2>
<table>
  <tr>
    <td>GET /v1/:resource</td>
    <td>List all objects of this type</td>
  </tr>
  <tr>
    <td>GET /v1/:resource/:id</td>
    <td>Retrieve a resource by id</td>
  </tr>
  <tr>
    <td>POST /v1/:resource</td>
    <td>Create a resource of this type</td>
  </tr>
  <tr>
    <td>PATCH /v1/:resource/:id</td>
    <td>Update the resource by id</td>
  </tr>
  <tr>
    <td>DELETE /v1/:resource/:id</td>
    <td>Delete the resource by id</td>
  </tr>
</table>
<hr />

<h1 id=\"roles\">Roles</h1>
<p>The Access Tokens will have owner permission on the account</p>
<hr />

<h1 id=\"filters\">Filters</h1>
<p>
  Some of the list endpoints allow to filter results by certain conditions.
  Refer to specific resources to find out what criteria are allowed. Below is a
  list of the different conditions.
</p>

<h4 id=\"eq\"><code>$eq</code></h4>
<p>Find all results matching the attribute value specified.</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[fieldName][$eq]=value</code></pre>
</div>
<p>Can also be simplified like this.</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[fieldName]=value</code></pre>
</div>

<h4 id=\"neq\"><code>$neq</code></h4>
<p>Find all results not matching the attribute value specified.</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[fieldName][$neq]=value</code></pre>
</div>

<h4 id=\"gt\"><code>$gt</code>, <code>$gte</code></h4>
<p>
  Find all results where the value is more (<code>$gt</code>) or more and equal
  (<code>$gte</code>) to a given value.
</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[startDate][$gte]=2020-01-01</code></pre>
</div>
<hr />

<h4 id=\"lt\"><code>$lt</code>, <code>$lte</code></h4>
<p>
  Find all results where the value is less (<code>$lt</code>) or less and equal
  (<code>$lte</code>) to a given value.
</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[startDate][$lte]=2020-01-01</code></pre>
</div>
<hr />

<h4 id=\"in\"><code>$in</code>, <code>$nin</code></h4>
<p>
  Find all results matching (<code>$in</code>) or not matching
  (<code>$nin</code>) any of the attribute values specified.
</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[fieldName][$in][]=value1&filters[fieldName][$in][]=value2</code></pre>
</div>
<hr />

<h4 id=\"between\"><code>$between</code></h4>
<p>Find all results between two values specified.</p>
<div>
  <pre><code class=\"language-shell\" data-lang=\"shell\">GET /v1/example?filters[startDate][$between][]=2020-01-01&filters[startDate][$between][]=2020-12-31</code></pre>
</div>
<hr />

<h1 id=\"versioning\">Versioning</h1>
<p>
  Each version of the API is guaranteed to be compatible with the resources of
  the same version. When we make breaking changes to the API a new version will
  be published
</p>
<hr />

<h1 id=\"changelog\">Changelog</h1>
<h3>2023-12-20</h3>
<p>Field [updated] added for filter & select for Get Many Employments and Get Many Employees.</p>
<h3>2021-03-15</h3>
<p>First draft was published</p>
<hr />

# Authentication

<!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: v1-preview
Contact: support@alexishr.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BadRequestResponse } from '../models';
// @ts-ignore
import { CreateTimesheetEntryRequest } from '../models';
// @ts-ignore
import { EmptyResponseMapped } from '../models';
// @ts-ignore
import { ForbiddenResponse } from '../models';
// @ts-ignore
import { InternalServerErrorResponse } from '../models';
// @ts-ignore
import { NotFoundResponse } from '../models';
// @ts-ignore
import { TimesheetEntriesGetManyResponseMapped } from '../models';
// @ts-ignore
import { TimesheetEntryGetOneResponseMapped } from '../models';
// @ts-ignore
import { TimesheetEntryResponseMapped } from '../models';
// @ts-ignore
import { TimesheetentryListManyEntriesFiltersParameter } from '../models';
// @ts-ignore
import { TimesheetentryListManyEntriesSortParameter } from '../models';
// @ts-ignore
import { UnauthorizedResponse } from '../models';
// @ts-ignore
import { UpdateTimesheetEntryRequest } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * TimesheetEntryApi - axios parameter creator
 * @export
 */
export const TimesheetEntryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create One TimesheetEntry
         * @summary Create One TimesheetEntry
         * @param {CreateTimesheetEntryRequest} createTimesheetEntryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOneEntry: async (createTimesheetEntryRequest: CreateTimesheetEntryRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createTimesheetEntryRequest' is not null or undefined
            assertParamExists('createOneEntry', 'createTimesheetEntryRequest', createTimesheetEntryRequest)
            const localVarPath = `/timesheet-entry`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: createTimesheetEntryRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/timesheet-entry',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(createTimesheetEntryRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete One TimesheetEntry
         * @summary Delete One TimesheetEntry
         * @param {string} id Resource Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOneEntry: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteOneEntry', 'id', id)
            const localVarPath = `/timesheet-entry/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/timesheet-entry/{id}',
                httpMethod: 'DELETE'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get One TimesheetEntry
         * @summary Get One TimesheetEntry
         * @param {string} id Resource Id
         * @param {Array<'id' | 'timesheetId' | 'typeId' | 'employeeId' | 'date' | 'updated' | 'status' | 'minutes' | 'note'>} [select] Select TimesheetEntry fields, comma-separated. (e.g. &#x60;select&#x3D;id,firstName,lastName,workEmail&#x60;)
         * @param {Array<'employee' | 'timesheet' | 'type'>} [relations] Select related TimesheetEntry resources, comma-separated. (e.g. &#x60;relations&#x3D;office,department&#x60;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOneEntry: async (id: string, select?: Array<'id' | 'timesheetId' | 'typeId' | 'employeeId' | 'date' | 'updated' | 'status' | 'minutes' | 'note'>, relations?: Array<'employee' | 'timesheet' | 'type'>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getOneEntry', 'id', id)
            const localVarPath = `/timesheet-entry/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (select) {
                localVarQueryParameter['select'] = select.join(COLLECTION_FORMATS.csv);
            }

            if (relations) {
                localVarQueryParameter['relations'] = relations.join(COLLECTION_FORMATS.csv);
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/timesheet-entry/{id}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Many TimesheetEntries
         * @summary Get Many TimesheetEntries
         * @param {Array<'id' | 'timesheetId' | 'typeId' | 'employeeId' | 'date' | 'updated' | 'status' | 'minutes' | 'note'>} [select] Select TimesheetEntry fields, comma-separated. (e.g. &#x60;select&#x3D;id,firstName,lastName,workEmail&#x60;)
         * @param {Array<'employee' | 'timesheet' | 'type'>} [relations] Select related TimesheetEntry resources, comma-separated. (e.g. &#x60;relations&#x3D;office,department&#x60;)
         * @param {TimesheetentryListManyEntriesFiltersParameter} [filters] Filters conditions per field. (e.g. &#x60;filters[id][$eq]&#x3D;507f1f77bcf86cd799439011&#x60;)
         * @param {number} [limit] Limit amount of received TimesheetEntries. (e.g. &#x60;limit&#x3D;20&#x60;)
         * @param {number} [offset] Offset amount of received TimesheetEntries. (e.g. &#x60;offset&#x3D;20&#x60;)
         * @param {TimesheetentryListManyEntriesSortParameter} [sort] Sort received TimesheetEntries by field. (e.g. &#x60;sort[id]&#x3D;asc&#x60;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listManyEntries: async (select?: Array<'id' | 'timesheetId' | 'typeId' | 'employeeId' | 'date' | 'updated' | 'status' | 'minutes' | 'note'>, relations?: Array<'employee' | 'timesheet' | 'type'>, filters?: TimesheetentryListManyEntriesFiltersParameter, limit?: number, offset?: number, sort?: TimesheetentryListManyEntriesSortParameter, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/timesheet-entry`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (select) {
                localVarQueryParameter['select'] = select.join(COLLECTION_FORMATS.csv);
            }

            if (relations) {
                localVarQueryParameter['relations'] = relations.join(COLLECTION_FORMATS.csv);
            }

            if (filters !== undefined) {
                localVarQueryParameter['filters'] = filters;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/timesheet-entry',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Replace One TimesheetEntry
         * @summary Replace One TimesheetEntry
         * @param {string} id Resource Id
         * @param {UpdateTimesheetEntryRequest} updateTimesheetEntryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOneEntry: async (id: string, updateTimesheetEntryRequest: UpdateTimesheetEntryRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateOneEntry', 'id', id)
            // verify required parameter 'updateTimesheetEntryRequest' is not null or undefined
            assertParamExists('updateOneEntry', 'updateTimesheetEntryRequest', updateTimesheetEntryRequest)
            const localVarPath = `/timesheet-entry/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: updateTimesheetEntryRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/timesheet-entry/{id}',
                httpMethod: 'PUT'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(updateTimesheetEntryRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update One TimesheetEntry
         * @summary Update One TimesheetEntry
         * @param {string} id Resource Id
         * @param {UpdateTimesheetEntryRequest} updateTimesheetEntryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOneEntry_1: async (id: string, updateTimesheetEntryRequest: UpdateTimesheetEntryRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateOneEntry_1', 'id', id)
            // verify required parameter 'updateTimesheetEntryRequest' is not null or undefined
            assertParamExists('updateOneEntry_1', 'updateTimesheetEntryRequest', updateTimesheetEntryRequest)
            const localVarPath = `/timesheet-entry/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: updateTimesheetEntryRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/timesheet-entry/{id}',
                httpMethod: 'PATCH'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(updateTimesheetEntryRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TimesheetEntryApi - functional programming interface
 * @export
 */
export const TimesheetEntryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TimesheetEntryApiAxiosParamCreator(configuration)
    return {
        /**
         * Create One TimesheetEntry
         * @summary Create One TimesheetEntry
         * @param {TimesheetEntryApiCreateOneEntryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOneEntry(requestParameters: TimesheetEntryApiCreateOneEntryRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TimesheetEntryResponseMapped>> {
            const createTimesheetEntryRequest: CreateTimesheetEntryRequest = {
                typeId: requestParameters.typeId,
                employeeId: requestParameters.employeeId,
                date: requestParameters.date,
                minutes: requestParameters.minutes,
                note: requestParameters.note
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOneEntry(createTimesheetEntryRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Delete One TimesheetEntry
         * @summary Delete One TimesheetEntry
         * @param {TimesheetEntryApiDeleteOneEntryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteOneEntry(requestParameters: TimesheetEntryApiDeleteOneEntryRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmptyResponseMapped>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteOneEntry(requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get One TimesheetEntry
         * @summary Get One TimesheetEntry
         * @param {TimesheetEntryApiGetOneEntryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOneEntry(requestParameters: TimesheetEntryApiGetOneEntryRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TimesheetEntryGetOneResponseMapped>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOneEntry(requestParameters.id, requestParameters.select, requestParameters.relations, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get Many TimesheetEntries
         * @summary Get Many TimesheetEntries
         * @param {TimesheetEntryApiListManyEntriesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listManyEntries(requestParameters: TimesheetEntryApiListManyEntriesRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TimesheetEntriesGetManyResponseMapped>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listManyEntries(requestParameters.select, requestParameters.relations, requestParameters.filters, requestParameters.limit, requestParameters.offset, requestParameters.sort, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Replace One TimesheetEntry
         * @summary Replace One TimesheetEntry
         * @param {TimesheetEntryApiUpdateOneEntryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateOneEntry(requestParameters: TimesheetEntryApiUpdateOneEntryRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TimesheetEntryResponseMapped>> {
            const updateTimesheetEntryRequest: UpdateTimesheetEntryRequest = {
                typeId: requestParameters.typeId,
                employeeId: requestParameters.employeeId,
                date: requestParameters.date,
                minutes: requestParameters.minutes,
                note: requestParameters.note
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateOneEntry(requestParameters.id, updateTimesheetEntryRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Update One TimesheetEntry
         * @summary Update One TimesheetEntry
         * @param {TimesheetEntryApiUpdateOneEntry0Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateOneEntry_1(requestParameters: TimesheetEntryApiUpdateOneEntry0Request, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TimesheetEntryResponseMapped>> {
            const updateTimesheetEntryRequest: UpdateTimesheetEntryRequest = {
                typeId: requestParameters.typeId,
                employeeId: requestParameters.employeeId,
                date: requestParameters.date,
                minutes: requestParameters.minutes,
                note: requestParameters.note
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateOneEntry_1(requestParameters.id, updateTimesheetEntryRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TimesheetEntryApi - factory interface
 * @export
 */
export const TimesheetEntryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TimesheetEntryApiFp(configuration)
    return {
        /**
         * Create One TimesheetEntry
         * @summary Create One TimesheetEntry
         * @param {TimesheetEntryApiCreateOneEntryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOneEntry(requestParameters: TimesheetEntryApiCreateOneEntryRequest, options?: AxiosRequestConfig): AxiosPromise<TimesheetEntryResponseMapped> {
            return localVarFp.createOneEntry(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete One TimesheetEntry
         * @summary Delete One TimesheetEntry
         * @param {TimesheetEntryApiDeleteOneEntryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOneEntry(requestParameters: TimesheetEntryApiDeleteOneEntryRequest, options?: AxiosRequestConfig): AxiosPromise<EmptyResponseMapped> {
            return localVarFp.deleteOneEntry(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Get One TimesheetEntry
         * @summary Get One TimesheetEntry
         * @param {TimesheetEntryApiGetOneEntryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOneEntry(requestParameters: TimesheetEntryApiGetOneEntryRequest, options?: AxiosRequestConfig): AxiosPromise<TimesheetEntryGetOneResponseMapped> {
            return localVarFp.getOneEntry(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Get Many TimesheetEntries
         * @summary Get Many TimesheetEntries
         * @param {TimesheetEntryApiListManyEntriesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listManyEntries(requestParameters: TimesheetEntryApiListManyEntriesRequest, options?: AxiosRequestConfig): AxiosPromise<TimesheetEntriesGetManyResponseMapped> {
            return localVarFp.listManyEntries(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Replace One TimesheetEntry
         * @summary Replace One TimesheetEntry
         * @param {TimesheetEntryApiUpdateOneEntryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOneEntry(requestParameters: TimesheetEntryApiUpdateOneEntryRequest, options?: AxiosRequestConfig): AxiosPromise<TimesheetEntryResponseMapped> {
            return localVarFp.updateOneEntry(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Update One TimesheetEntry
         * @summary Update One TimesheetEntry
         * @param {TimesheetEntryApiUpdateOneEntry0Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOneEntry_1(requestParameters: TimesheetEntryApiUpdateOneEntry0Request, options?: AxiosRequestConfig): AxiosPromise<TimesheetEntryResponseMapped> {
            return localVarFp.updateOneEntry_1(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createOneEntry operation in TimesheetEntryApi.
 * @export
 * @interface TimesheetEntryApiCreateOneEntryRequest
 */
export type TimesheetEntryApiCreateOneEntryRequest = {
    
} & CreateTimesheetEntryRequest

/**
 * Request parameters for deleteOneEntry operation in TimesheetEntryApi.
 * @export
 * @interface TimesheetEntryApiDeleteOneEntryRequest
 */
export type TimesheetEntryApiDeleteOneEntryRequest = {
    
    /**
    * Resource Id
    * @type {string}
    * @memberof TimesheetEntryApiDeleteOneEntry
    */
    readonly id: string
    
}

/**
 * Request parameters for getOneEntry operation in TimesheetEntryApi.
 * @export
 * @interface TimesheetEntryApiGetOneEntryRequest
 */
export type TimesheetEntryApiGetOneEntryRequest = {
    
    /**
    * Resource Id
    * @type {string}
    * @memberof TimesheetEntryApiGetOneEntry
    */
    readonly id: string
    
    /**
    * Select TimesheetEntry fields, comma-separated. (e.g. `select=id,firstName,lastName,workEmail`)
    * @type {Array<'id' | 'timesheetId' | 'typeId' | 'employeeId' | 'date' | 'updated' | 'status' | 'minutes' | 'note'>}
    * @memberof TimesheetEntryApiGetOneEntry
    */
    readonly select?: Array<'id' | 'timesheetId' | 'typeId' | 'employeeId' | 'date' | 'updated' | 'status' | 'minutes' | 'note'>
    
    /**
    * Select related TimesheetEntry resources, comma-separated. (e.g. `relations=office,department`)
    * @type {Array<'employee' | 'timesheet' | 'type'>}
    * @memberof TimesheetEntryApiGetOneEntry
    */
    readonly relations?: Array<'employee' | 'timesheet' | 'type'>
    
}

/**
 * Request parameters for listManyEntries operation in TimesheetEntryApi.
 * @export
 * @interface TimesheetEntryApiListManyEntriesRequest
 */
export type TimesheetEntryApiListManyEntriesRequest = {
    
    /**
    * Select TimesheetEntry fields, comma-separated. (e.g. `select=id,firstName,lastName,workEmail`)
    * @type {Array<'id' | 'timesheetId' | 'typeId' | 'employeeId' | 'date' | 'updated' | 'status' | 'minutes' | 'note'>}
    * @memberof TimesheetEntryApiListManyEntries
    */
    readonly select?: Array<'id' | 'timesheetId' | 'typeId' | 'employeeId' | 'date' | 'updated' | 'status' | 'minutes' | 'note'>
    
    /**
    * Select related TimesheetEntry resources, comma-separated. (e.g. `relations=office,department`)
    * @type {Array<'employee' | 'timesheet' | 'type'>}
    * @memberof TimesheetEntryApiListManyEntries
    */
    readonly relations?: Array<'employee' | 'timesheet' | 'type'>
    
    /**
    * Filters conditions per field. (e.g. `filters[id][$eq]=507f1f77bcf86cd799439011`)
    * @type {TimesheetentryListManyEntriesFiltersParameter}
    * @memberof TimesheetEntryApiListManyEntries
    */
    readonly filters?: TimesheetentryListManyEntriesFiltersParameter
    
    /**
    * Limit amount of received TimesheetEntries. (e.g. `limit=20`)
    * @type {number}
    * @memberof TimesheetEntryApiListManyEntries
    */
    readonly limit?: number
    
    /**
    * Offset amount of received TimesheetEntries. (e.g. `offset=20`)
    * @type {number}
    * @memberof TimesheetEntryApiListManyEntries
    */
    readonly offset?: number
    
    /**
    * Sort received TimesheetEntries by field. (e.g. `sort[id]=asc`)
    * @type {TimesheetentryListManyEntriesSortParameter}
    * @memberof TimesheetEntryApiListManyEntries
    */
    readonly sort?: TimesheetentryListManyEntriesSortParameter
    
}

/**
 * Request parameters for updateOneEntry operation in TimesheetEntryApi.
 * @export
 * @interface TimesheetEntryApiUpdateOneEntryRequest
 */
export type TimesheetEntryApiUpdateOneEntryRequest = {
    
    /**
    * Resource Id
    * @type {string}
    * @memberof TimesheetEntryApiUpdateOneEntry
    */
    readonly id: string
    
} & UpdateTimesheetEntryRequest

/**
 * Request parameters for updateOneEntry_1 operation in TimesheetEntryApi.
 * @export
 * @interface TimesheetEntryApiUpdateOneEntry0Request
 */
export type TimesheetEntryApiUpdateOneEntry0Request = {
    
    /**
    * Resource Id
    * @type {string}
    * @memberof TimesheetEntryApiUpdateOneEntry0
    */
    readonly id: string
    
} & UpdateTimesheetEntryRequest

/**
 * TimesheetEntryApiGenerated - object-oriented interface
 * @export
 * @class TimesheetEntryApiGenerated
 * @extends {BaseAPI}
 */
export class TimesheetEntryApiGenerated extends BaseAPI {
    /**
     * Create One TimesheetEntry
     * @summary Create One TimesheetEntry
     * @param {TimesheetEntryApiCreateOneEntryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TimesheetEntryApiGenerated
     */
    public createOneEntry(requestParameters: TimesheetEntryApiCreateOneEntryRequest, options?: AxiosRequestConfig) {
        return TimesheetEntryApiFp(this.configuration).createOneEntry(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete One TimesheetEntry
     * @summary Delete One TimesheetEntry
     * @param {TimesheetEntryApiDeleteOneEntryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TimesheetEntryApiGenerated
     */
    public deleteOneEntry(requestParameters: TimesheetEntryApiDeleteOneEntryRequest, options?: AxiosRequestConfig) {
        return TimesheetEntryApiFp(this.configuration).deleteOneEntry(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get One TimesheetEntry
     * @summary Get One TimesheetEntry
     * @param {TimesheetEntryApiGetOneEntryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TimesheetEntryApiGenerated
     */
    public getOneEntry(requestParameters: TimesheetEntryApiGetOneEntryRequest, options?: AxiosRequestConfig) {
        return TimesheetEntryApiFp(this.configuration).getOneEntry(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get Many TimesheetEntries
     * @summary Get Many TimesheetEntries
     * @param {TimesheetEntryApiListManyEntriesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TimesheetEntryApiGenerated
     */
    public listManyEntries(requestParameters: TimesheetEntryApiListManyEntriesRequest, options?: AxiosRequestConfig) {
        return TimesheetEntryApiFp(this.configuration).listManyEntries(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Replace One TimesheetEntry
     * @summary Replace One TimesheetEntry
     * @param {TimesheetEntryApiUpdateOneEntryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TimesheetEntryApiGenerated
     */
    public updateOneEntry(requestParameters: TimesheetEntryApiUpdateOneEntryRequest, options?: AxiosRequestConfig) {
        return TimesheetEntryApiFp(this.configuration).updateOneEntry(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update One TimesheetEntry
     * @summary Update One TimesheetEntry
     * @param {TimesheetEntryApiUpdateOneEntry0Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TimesheetEntryApiGenerated
     */
    public updateOneEntry_1(requestParameters: TimesheetEntryApiUpdateOneEntry0Request, options?: AxiosRequestConfig) {
        return TimesheetEntryApiFp(this.configuration).updateOneEntry_1(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
